language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - curl --retry 3 --location http://box-project.org/installer.php
  - curl --retry 3 --location http://box-project.org/installer.php | php
  - php box.phar build

script:
  - php bin/depicter
  - php depicter.phar
